version: '3'

services:
  postgres:
    platform: linux/amd64
    image: postgres:15.1
    env_file: [ .env ]
    restart: always
    ports:
      - "5454:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}


  app:
    platform: linux/amd64
    env_file: [ .env ]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
